version: '3.7'
volumes:
  dependency-track:


services:
  dtrack-apiserver:
    image: dependencytrack/apiserver:4.5.0
    container_name: dtrack-apiserver
    deploy:
      resources:
        limits:
          memory: 12288m
        reservations:
          memory: 8192m
      restart_policy:
        condition: on-failure
    ports:
      - '8081:8080'
    volumes:
      - 'dependency-track:/data'
    restart: unless-stopped
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - '8085:8080'
    environment:
      SWAGGER_JSON_URL: http://localhost:8081/api/swagger.json
